CREATE TABLE CUSTOMER.CUSTOMER_DEMOGRAPHY (
  CIF BIGINT NOT NULL PRIMARY KEY,
  NAME VARCHAR,
  BIRTHDATE VARCHAR,
  GENDER VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,

  -- Bank Product
  PRODUCTID BIGINT,
  PRODUCTTYPE VARCHAR,
  OPENDATE VARCHAR,
  STATUS VARCHAR,

  -- Asset
  ASSETID BIGINT,
  ASSETTYPE VARCHAR,
  ASSETVALUE DECIMAL,
  VALUATION_DATE VARCHAR
)SALT_BUCKET=6,
COMPRESSION=snappy;
